namespace Koz.Windows.Forms.Tools
{
    public enum DateTimePickerMessage
    {
        DTM_FIRST = 0x1000,
        DTM_GETSYSTEMTIME = DTM_FIRST + 1,
        DTM_SETSYSTEMTIME = DTM_FIRST + 2,
        DTM_GETRANGE = DTM_FIRST + 3,
        DTM_SETRANGE = DTM_FIRST + 4,
        DTM_SETFORMATA = DTM_FIRST + 5,
        DTM_SETFORMATW = DTM_FIRST + 50,
        DTM_SETMCCOLOR = DTM_FIRST + 6,
        DTM_GETMCCOLOR = DTM_FIRST + 7,
        DTM_GETMONTHCAL = DTM_FIRST + 8,
        DTM_SETMCFONT = DTM_FIRST + 9,
        DTM_GETMCFONT = DTM_FIRST + 10,
        DTM_SETMCSTYLE = DTM_FIRST + 11,
        DTM_GETMCSTYLE = DTM_FIRST + 12,
        DTM_CLOSEMONTHCAL = DTM_FIRST + 13,
        DTM_GETDATETIMEPICKERINFO = DTM_FIRST + 14,
        DTM_GETIDEALSIZE = DTM_FIRST + 15,
    }
}
